#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Custom Project Relative Bin Executables
alias \
    px="./.venv/bin/python" \

# add this if were using laravel phpunit
# t="./vendor/bin/phpunit" \

##################################################
### Checking If Commands if Found in Our ENV $PATH
##################################################

# npm aliases
if [ -x "$(command -v npm)" ]; then
alias \
    lb="npm run build" \
    cms="npm run cms" \
    nls="npm run serve" \
    ;
fi

# netlify aliases
if [ -x "$(command -v netlify)" ]; then
alias \
    nb="netlify build --context=prod" \
    dev="netlify dev" \
    nd="netlify deploy --prod" \
    ;
fi

# hugo aliases
if [ -x "$(command -v hugo)" ]; then
alias \
    hhh="hugo server -s exampleSite --themesDir=../.. --disableFastRender" \
    htb="hugo -s exampleSite --gc --minify --themesDir ../.." \
    ;
fi

# rust alias
if [ -x "$(command -v cargo)" ]; then
alias \
    rs="cargo" \
    ;
fi

# vlang alias
if [ -x "$(command -v v)" ]; then
alias \
    vc="v run" \
    ;
fi

# youtube-viewer alias
if [ -x "$(command -v youtube-viewer)" ]; then
alias \
    YT="youtube-viewer" \
    ;
fi

# youtube-dl aliases
if [ -x "$(command -v youtube-dl)" ]; then
alias \
    yt="youtube-dl --add-metadata -i" \
    yt4="youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4'"
	yta="yt -x -f bestaudio/best --audio-format mp3" \
	;
fi

# This alias is important. It enables the `pauseallmpv` command.
if [ -x "$(command -v mpv)" ]; then
alias \
    mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
    ;
fi

# remove banner for videos
if [ -x "$(command -v ffmpeg)" ]; then
alias \
    ffmpeg="ffmpeg -hide_banner" \
    ;
fi

# neovim aliases
if [ -x "$(command -v nvim)" ]; then
alias \
    sv="sudo nvim" \
	magit="nvim -c MagitOnly" \
	;
fi

# journal alias
if [ -x "$(command -v jrnl)" ]; then
alias \
    j="jrnl" \
    ;
fi

# sxiv alias
if [ -x "$(command -v sxiv)" ]; then
alias \
    x="sxiv -ft *" \
    ;
fi

# git aliases
#     gs="git status" \
#     important to remove dd alias if you need to use that command
if [ -x "$(command -v git)" ]; then
alias \
    g="git" \
	gl="git log --all --decorate --oneline --graph" \
	gd="git diff" \
	gam="git commit -am" \
	gaa="git add ." \
	ss="git status" \
	dd="git diff" \
	ginit="git init && git add . && git commit -m 'init'" \
	nah="git reset --hard;git clean -df" \
	wip="git add . && git commit -m 'wip'" \
	dot="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME add" \
	dots="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME status" \
	dif="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME diff" \
    dop="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME push" \
    com="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME commit" \
	diff="diff --color=auto" \
	basic="git --git-dir=/home/uriah/THRIFTSHOP/basic-functions/.git/ --work-tree=/home/uriah/THRIFTSHOP/basic-functions" \
	;
fi

# Replacement for ls command aliases
if [ -x "$(command -v exa)" ]; then
alias \
    l="exa -l --color=always --group-directories-first" \
    ls="exa -D --color=always --group-directories-first" \
	ll="exa -l --color=always --group-directories-first" \
	la="exa -FSal --color=always --group-directories-first" \
	;
else
    l="ls" \
    ls="ls -d */" \
    ll="ls -lh" \
    la="ls -la" \
fi

# Alternative to cat command
if [ -x "$(command -v bat)" ]; then
alias \
    b="bat" \
    ;
fi

# Clipboard Aliases
if [ -x "$(command -v xclip)" ]; then
alias \
    pbcopy="xclip -sel clip" \
	cwd="pwd | xclip -sel clip" \
    ;
fi

################################################################
### Commands Here are Already Available in Our System by Default
################################################################

# Directories Aliases
# navigation
alias ..='cd ..'
alias ...='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'


# File System Aliases
alias \
    r="$FILE" \
	c="clear" \
	e="xdg-open" \
    grep="grep --color=auto" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	rf="rm -rf" \
	mkd="mkdir -pv" \
	hsc="history -c" \
	path="echo -e ${PATH//:/\\\n}" \

# Permissions aliases
alias \
	chax="sudo chmod a+x" \
	chx="chmod +x" \
	000="sudo chmod 000" \
	644="sudo chmod 644" \
	600="sudo chmod 600" \
	750="sudo chmod 750" \
	755="sudo chmod 755" \
	775="sudo chmod 775" \
	777="sudo chmod 777" \
	mine="sudo chown -R $(whoami)" \
	root="sudo su -" \
	sudofy="sudo chown -R root" \
	perm="stat --printf '%a %n \n'" \

# System commands Aliases
alias \
	p="sudo pacman" \
	SS="sudo systemctl" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc; source ~/.config/aliasrc;" \
	gpgr="gpg-connect-agent RELOADAGENT /bye" \
	pp="pacman -Slq | fzf -m --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S" \
	pq="sudo pacman -Qtdq" \
    ys="yay -Slq | fzf -m --preview 'yay -Si {1}'| xargs -ro yay -S" \
    yr="yay -Qeq | fzf -m --preview 'yay -Qi {1}' | xargs -ro yay -Rs" \
	ka="killall" \

alias pacsyu='sudo pacman -Syyu'                 # update only standard pkgs
alias yaysua="yay -Sua --noconfirm"              # update only AUR pkgs
alias yaysyu="yay -Syu --noconfirm"              # update standard pkgs and AUR pkgs
alias unlock="sudo rm /var/lib/pacman/db.lck"    # remove pacman lock
alias cleanup='sudo pacman -Rns $(pacman -Qtdq)' # remove orphaned packages

# get error messages from journalctl
alias jctl="journalctl -p 3 -xb"
# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# youtube-dl
alias yta-aac="youtube-dl --extract-audio --audio-format aac "
alias yta-best="youtube-dl --extract-audio --audio-format best "
alias yta-flac="youtube-dl --extract-audio --audio-format flac "
alias yta-m4a="youtube-dl --extract-audio --audio-format m4a "
alias yta-mp3="youtube-dl --extract-audio --audio-format mp3 "
alias yta-opus="youtube-dl --extract-audio --audio-format opus "
alias yta-vorbis="youtube-dl --extract-audio --audio-format vorbis "
alias yta-wav="youtube-dl --extract-audio --audio-format wav "
alias ytv-best="youtube-dl -f bestvideo+bestaudio "

# switch between shells
alias tobash="sudo chsh $USER -s /bin/bash && echo 'Now log out.'"
alias tozsh="sudo chsh $USER -s /bin/zsh && echo 'Now log out.'"
alias tofish="sudo chsh $USER -s /bin/fish && echo 'Now log out.'"

# get top process eating cpu
alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'

## get top process eating memory
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
