#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Custom Project Relative Bin Executables
alias \
    px="./.venv/bin/python" \

# Node Modules Installed Via FNM cant be found in $PATH
# So We Are Creating an Alias Anyway without checking
# If we Have those commands, We Know We Installed These Cmds
alias \
    nb="netlify build --context=prod" \
    dev="netlify dev" \
    nd="netlify deploy --prod" \
    lb="npm run build" \
    cms="npm run cms" \
    nls="npm run serve" \

########################################################################
### Checking If We have The Commands in Our System Before We Add Aliases
########################################################################


# hugo aliases
if [ -x "$(command -v hugo)" ]; then
alias \
    hhh="hugo server -s exampleSite --themesDir=../.. --disableFastRender" \
    htb="hugo -s exampleSite --gc --minify --themesDir ../.." \
    ;
fi

# rust alias
if [ -x "$(command -v cargo)" ]; then
alias \
    rs="cargo" \
    ;
fi

# vlang alias
if [ -x "$(command -v v)" ]; then
alias \
    vc="v run" \
    ;
fi

# youtube-viewer alias
if [ -x "$(command -v youtube-viewer)" ]; then
alias \
    YT="youtube-viewer" \
    ;
fi

# youtube-dl aliases
if [ -x "$(command -v youtube-dl)" ]; then
alias \
    yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best --audio-format mp3" \
	;
fi

# This alias is important. It enables the `pauseallmpv` command.
if [ -x "$(command -v mpv)" ]; then
alias \
    mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
    ;
fi

# remove banner for videos
if [ -x "$(command -v ffmpeg)" ]; then
alias \
    ffmpeg="ffmpeg -hide_banner" \
    ;
fi

# neovim aliases
if [ -x "$(command -v nvim)" ]; then
alias \
    sv="sudo nvim" \
	magit="nvim -c MagitOnly" \
	;
fi

# journal alias
if [ -x "$(command -v jrnl)" ]; then
alias \
    j="jrnl" \
    ;
fi

# sxiv alias
if [ -x "$(command -v sxiv)" ]; then
alias \
    x="sxiv -ft *" \
    ;
fi

# git aliases
if [ -x "$(command -v git)" ]; then
alias \
    g="git" \
    gs="git status" \
	gl="git log --all --decorate --oneline --graph" \
	gd="git diff" \
	gam="git commit -am" \
	gaa="git add ." \
	ginit="git init && git add . && git commit -m 'init'" \
	nah="git reset --hard;git clean -df" \
	wip="git add . && git commit -m 'wip'" \
	dot="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME add" \
	dots="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME status" \
	dif="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME diff" \
    dop="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME push" \
    com="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME commit" \
	diff="diff --color=auto" \
	;
fi

# Replacement for ls command aliases
if [ -x "$(command -v exa)" ]; then
alias \
    l="exa -l --color=always --group-directories-first" \
    ls="exa -D --color=always --group-directories-first" \
	ll="exa -l --color=always --group-directories-first" \
	la="exa -a --color=always --group-directories-first" \
	;
else
    l="ls" \
    ls="ls -d */" \
    ll="ls -lh" \
    la="ls -la" \
fi

# Alternative to cat command
if [ -x "$(command -v bat)" ]; then
alias \
    b="bat" \
    ;
fi

# Clipboard Aliases
if [ -x "$(command -v xclip)" ]; then
alias \
    pbcopy="xclip -sel clip" \
	cwd="pwd | xclip -sel clip" \
    ;
fi

################################################################
### Commands Here are Already Available in Our System by Default
################################################################

# Directories Aliases
alias \
	..="cd .." \
	...="cd ../.." \
	....="cd ../../.." \
	.....="cd ../../../.." \
	......="cd ../../../.." \

# File System Aliases
alias \
    r="$FILE" \
	c="clear" \
	e="xdg-open" \
    grep="grep --color=auto" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	rf="rm -rf" \
	mkd="mkdir -pv" \
	hsc="history -c" \
	path="echo -e ${PATH//:/\\\n}" \

# Permissions aliases
alias \
	chax="sudo chmod a+x" \
	chx="chmod +x" \
	000="sudo chmod 000" \
	644="sudo chmod 644" \
	600="sudo chmod 600" \
	755="sudo chmod 755" \
	775="sudo chmod 775" \
	777="sudo chmod 777" \
	mine="sudo chown -R $(whoami)" \
	sudofy="sudo chown -R root" \
	perm="stat --printf '%a %n \n'" \

# System commands Aliases
alias \
	p="sudo pacman" \
	SS="sudo systemctl" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc; source ~/.config/aliasrc;" \
	gpgr="gpg-connect-agent RELOADAGENT /bye" \
	pp="pacman -Slq | fzf -m --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S" \
	pq="sudo pacman -Qtdq" \
    ys="yay -Slq | fzf -m --preview 'yay -Si {1}'| xargs -ro yay -S" \
    yr="yay -Qeq | fzf -m --preview 'yay -Qi {1}' | xargs -ro yay -Rs" \
	ka="killall" \
